name: build-and-deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Testar valor de DEPLOY_HOST
        run: |
          echo -e "Host: ${{ secrets.DEPLOY_HOST }}"

      - name: Checkout do c√≥digo
        uses: actions/checkout@v3

      - name: Instalar depend√™ncias
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Criar chave SSH e testar conex√£o
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

          echo "üîç Testando conex√£o SSH..."
          ssh -v -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} exit

      - name: Copiar arquivos via SCP
        run: |
          scp -r dist/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}